### ISSUE TITLE
BCA problem

### ISSUE THREAD

**Issue by fsonntag** [batzner/allergenius#1]
While looking at the code, I got an allergic reaction. I guess it came from my BCA (bad code allergy).
Also the bot didn't recognize this while I asked it I wanted to eat some code.

**Comment by batzner** [comment]
Fixed

**Comment by fsonntag** [comment]
Can you provide the code that fixed this issue?

**Comment by batzner** [comment]
Don't talk back to me or I will make this closed source.

**Comment by fsonntag** [comment]
Screenshot is already taken! This will go viral!
